#!/bin/sh
. /lib/init/rc.lib

case "${1}" in
    start)
        log "Starting Getty..."
        {
            for i in $(seq 1 6);do
                while :;do getty 115200 "tty${i}";done &
            done
            while :;do getty 38400 ttyS0;done &
        } > /dev/null 2>&1
        ;;
esac
