#!/bin/sh
. /lib/init/rc.lib

case "${1}" in
    start)
        log "Starting Networking..."
        ip l set dev lo up
        for DEVICE in /sys/class/net/*;do
            log_info "Found network device ${DEVICE##*/}"
            ip link set ${DEVICE##*/} up
            case ${DEVICE##*/} in
                lo) ;;
                sit*) ;;
                *) udhcpc -b -i ${DEVICE##*/} -s /lib/init/dhcp > /dev/null 2>&1 & ;;
            esac
        done
        ;;
    stop)
        log "Stopping Networking..."
        for DEVICE in /sys/class/net/*;do
            ip link set ${DEVICE##*/} down
        done
        ;;
    restart)
        "${0}" stop
        "${0}" start
        ;;
esac
